server:
  port: 9998

spring:
  application:
    name: demo-provider

eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/