server:
  port: 9996

spring:
  application:
    name: demo_zuul

eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #服务注册中心地址

zuul:
  prefix: /demo
  ignored-services: "*"
  routes:
    consumer:
      path: /myconsumer/**
      serviceId: demo-consumer
